"""
Module: specimen.py

Purpose:
    Defines the specimen models for the assay database.
    A specimen is the biological material loaded into a well.
    This module uses joined-table inheritance to represent four distinct specimen types
    (HumanDonor, MouseDonor, Virus, Bacteria) under a common Specimen base table.
    It also defines supporting reference tables: Anticoagulant, CellType, CellCharacteristics.

Inheritance design:
    - Specimen is the base table; every specimen of any type gets a row there.
    - Each subtype (HumanDonor, MouseDonor, Virus, Bacteria) has its own table with
      type-specific columns, linked to specimens.id via a FK primary key.
    - A shared sequence (specimen_id_seq) generates IDs consistently across all subtypes.
    - The `type` discriminator column on Specimen routes ORM queries to the correct subclass.

Cardinality:
    - One specimen can appear in many wells (a donor blood sample may be plated multiple times).
    - HumanDonor and MouseDonor each belong to one Anticoagulant, one CellType, one CellCharacteristics.
    - One Anticoagulant can be referenced by many HumanDonors and MouseDonors.
    - CellType and CellCharacteristics are simple lookup/reference tables.

Key Design Decisions:
    - Joined-table inheritance keeps common fields in specimens and type-specific fields separate.
    - Anticoagulant.hash uses a partial unique index: hash is unique only when it is not 'non available',
      which allows unknown anticoagulants to be stored without collapsing them into one record.
    - CellCharacteristics.name maps to the DB column 'characteristic_name' to avoid name collisions.
"""

from sqlalchemy import Integer, String, Column, ForeignKey, Sequence, Float, Boolean, Index, text
from sqlalchemy.orm import relationship
from database import Base

# Shared sequence for unique IDs across all specimen types
specimen_id_seq = Sequence('specimen_id_seq', start=1)

class Specimen(Base):
    """
    Base specimen table. Every specimen of any type has a row here.

    Attributes:
        id (int): Primary key, generated by the shared specimen_id_seq sequence.
        type (str): Discriminator column. Values: 'human', 'mouse', 'virus', 'bacteria'.

    Relationships:
        wells: One-to-many. A specimen can appear in many wells across different plates.

    Notes:
        This table uses joined-table inheritance. Subtype-specific columns live in
        human_donor, mouse_donor, virus, and bacteria tables respectively.
    """

    __tablename__ = "specimens"  # Must be a real table for inheritance
    id = Column(Integer, specimen_id_seq, primary_key=True, server_default=specimen_id_seq.next_value())
    type = Column(String(50), nullable=False)  # "human", "mouse", "virus", "bacteria"


    wells = relationship("Well", back_populates="specimen")
    
    
    __mapper_args__ = {
        'polymorphic_identity': 'specimen',
        'polymorphic_on': type
    }

    def __repr__(self):
        return f"<Specimen(id={self.id}, type='{self.type}')>"


class HumanDonor(Specimen):
    """
    Represents a human blood donor specimen.

    Attributes:
        id (int): Primary key, FK to specimens.id.
        name (str): Donor identifier. Required.
        weight_kg (float): Donor weight in kilograms.
        height_cm (float): Donor height in centimetres.
        smoker (bool): Whether the donor is a smoker.
        ethnicity (str): Donor ethnicity.
        blood_type (str): ABO/Rh blood type (e.g. 'A+', 'O-').
        anticoagulant_id (int): FK to anticoagulant table.
        cell_type_id (int): FK to cell_type table. Required.
        cell_characteristic_id (int): FK to cell_characteristics table. Required.
        age (int): Donor age.
        sex (str): Biological sex ('M' or 'F').

    Relationships:
        anticoagulant: Many-to-one. The anticoagulant used for blood collection.
        cell_type: Many-to-one. The cell type isolated from this donor.
        cell_characteristic: Many-to-one. Additional cell characterisation (e.g. CD4+).
    """

    __tablename__ = "human_donor"
    id = Column(Integer, ForeignKey("specimens.id"), primary_key=True)

    name = Column(String(100), nullable=False)
    weight_kg = Column(Float)
    height_cm = Column(Float)
    smoker = Column(Boolean)
    ethnicity = Column(String(100))
    blood_type = Column(String(10))
    anticoagulant_id = Column(Integer, ForeignKey("anticoagulant.id"))
    cell_type_id = Column(Integer, ForeignKey("cell_type.id"), nullable=False)
    cell_characteristic_id = Column(Integer, ForeignKey("cell_characteristics.id"), nullable=False)
    age = Column(Integer)
    sex = Column(String(1))

    # Relationships
    anticoagulant = relationship("Anticoagulant", back_populates="human_donors")
    cell_type = relationship("CellType")
    cell_characteristic = relationship("CellCharacteristics")

    __mapper_args__ = {
        'polymorphic_identity': 'human',
    }


class MouseDonor(Specimen):
    """
    Represents a mouse donor specimen.

    Attributes:
        id (int): Primary key, FK to specimens.id.
        name (str): Mouse identifier. Required.
        anticoagulant_id (int): FK to anticoagulant table.
        cell_type_id (int): FK to cell_type table. Required.
        cell_characteristic_id (int): FK to cell_characteristics table. Required.
        strain (str): Mouse strain (e.g. 'C57BL/6').
        transgene (str): Transgene information if applicable.

    Relationships:
        anticoagulant: Many-to-one. The anticoagulant used for blood collection.
        cell_type: Many-to-one. The cell type isolated from this donor.
        cell_characteristic: Many-to-one. Additional cell characterisation.
    """

    __tablename__ = "mouse_donor"
    id = Column(Integer, ForeignKey("specimens.id"), primary_key=True)

    name = Column(String(100), nullable=False)
    anticoagulant_id = Column(Integer, ForeignKey("anticoagulant.id"))
    cell_type_id = Column(Integer, ForeignKey("cell_type.id"), nullable=False)
    cell_characteristic_id = Column(Integer, ForeignKey("cell_characteristics.id"), nullable=False)
    strain = Column(String(50))
    transgene = Column(String(50))

    # Relationships
    anticoagulant = relationship("Anticoagulant", back_populates="mouse_donors")
    cell_type = relationship("CellType")
    cell_characteristic = relationship("CellCharacteristics")
    #wells = relationship("Well", back_populates="specimen")

    __mapper_args__ = {
        'polymorphic_identity': 'mouse',
    }


class Virus(Specimen):
    """
    Represents a viral specimen used in infection/stimulation experiments.

    Attributes:
        id (int): Primary key, FK to specimens.id.
        name (str): Virus name. Required.
        category_type (str): Genome type stored as DB column 'type'. Values: 'DNA', 'RNA'.
    """

    __tablename__ = "virus"
    id = Column(Integer, ForeignKey("specimens.id"), primary_key=True)
    name = Column(String(100), nullable=False)
    category_type = Column("type", String(50))  # "DNA", "RNA"

    __mapper_args__ = {
        'polymorphic_identity': 'virus'
    }


class Bacteria(Specimen):
    """
    Represents a bacterial specimen used in infection/stimulation experiments.

    Attributes:
        id (int): Primary key, FK to specimens.id.
        name (str): Bacteria name. Required.
        category_type (str): Gram stain type stored as DB column 'type'. Values: 'gram+', 'gram-'.
    """

    __tablename__ = "bacteria"
    id = Column(Integer, ForeignKey("specimens.id"), primary_key=True)
    name = Column(String(100), nullable=False)
    category_type = Column("type", String(50))  # "gram+", "gram-"

    __mapper_args__ = {
        'polymorphic_identity': 'bacteria'
    }


class Anticoagulant(Base):
    """
    Reference table for anticoagulants used during blood collection.

    Attributes:
        id (int): Primary key.
        hash (str): PubChem SHA-256 hash (first 8 chars) for known substances.
                    Set to 'non available' for unknown anticoagulants.
        anticoagulant_name (str): Name of the anticoagulant. Required.

    Relationships:
        human_donors: One-to-many. Human donors collected with this anticoagulant.
        mouse_donors: One-to-many. Mouse donors collected with this anticoagulant.

    Constraints:
        Partial unique index on hash: hash must be unique only when it is NOT 'non available'.
        This allows multiple distinct unknown anticoagulants to coexist without collapsing.
    """

    __tablename__ = "anticoagulant"
    __table_args__ = (
        Index(
            "uq_anticoagulant_hash_known",
            "hash",
            unique=True,
            postgresql_where=text("hash <> 'non available'"),
        ),
    )
    id = Column(Integer, primary_key=True, autoincrement=True)
    hash = Column(String(64), nullable=False)
    anticoagulant_name = Column(String(100), nullable=False)

    human_donors = relationship("HumanDonor", back_populates="anticoagulant")
    mouse_donors = relationship("MouseDonor", back_populates="anticoagulant")


class CellType(Base):
    """
    Lookup table for cell types isolated from donors.

    Attributes:
        id (int): Primary key.
        name (str): Cell type name. Required and unique. Examples: 'PBMC', 'liver', 'neurons'.
    """

    __tablename__ = "cell_type"
    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(50), nullable=False, unique=True)  # "PBMC", "liver", "neurons"


class CellCharacteristics(Base):
    """
    Lookup table for additional cell characterisation markers.

    Attributes:
        id (int): Primary key.
        name (str): Characteristic label. Required and unique. Examples: 'CD4+', 'CD8+'.
                    Maps to the DB column 'characteristic_name'.
    """

    __tablename__ = "cell_characteristics"
    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column("characteristic_name", String(100), nullable=False, unique=True)  # "CD4+", "CD8+", etc.
